version: '3.8'

services:
  postgres:
    image: postgres:15
    profiles: [front-dev, prod]
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend-app:
    build: frontend
    profiles: [front-dev]
    ports:
      - "5175:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-app

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    profiles: [prod]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /app/node_modules
      - /etc/letsencrypt/archive/paltus-edu.ru/fullchain1.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/archive/paltus-edu.ru/privkey1.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - backend-app

  backend-app:
    build: backend
    profiles: [front-dev, prod]
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      GIGA_CHAT_API_KEY: ${GIGA_CHAT_API_KEY}
    depends_on:
      - postgres

volumes:
  postgres_data: