name: Java CI with Maven

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        working-directory: ./backend
        run: mvn -B verify -e -X
        env:
          SPRING_PROFILES_ACTIVE: test
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            backend/target/surefire-reports
            backend/target/logs

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: self-hosted
    steps:
      - name: Clone repo
        run: |
          rm -rf PALTUS || true
          git clone https://github.com/IU-Capstone-Project-2025/PALTUS.git
          cp ~/actions-runner/environment/.env PALTUS/.env
          cd PALTUS
          git checkout ${{ github.ref_name }}

      - name: Docker compose
        run: |
          cd PALTUS/backend
          docker compose down
          docker compose up -d --build